pipeline {
    agent any

    tools {
    maven 'Maven-3.9.12'
    jdk 'jdk-21.0.10'
}


    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/enoch417gthub/enoch-4th-devops/tree/main/hello-world-enoch.git'
                 
            }
        }

        stage('Build with Maven') {
            steps {
                bat 'mvn clean package'
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                deploy adapters: [
                    tomcat9(
                        credentialsId: 'tomcat-creds',
                        path: '',
                        url: 'http://localhost:8081'
                    )
                ],
                contextPath: 'hello-world-enoch',
                war: 'target/hello-world-enoch.war'
            }
        }
    }
}
